// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAXRu2plQtOQVNsPebOwk3ExZCOrgKgoA',
    appId: '1:870875139309:web:66296ff95a693466bb50e4',
    messagingSenderId: '870875139309',
    projectId: 'contact-app-9cc96',
    authDomain: 'contact-app-9cc96.firebaseapp.com',
    storageBucket: 'contact-app-9cc96.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBq1pwqdot1Y8eJMxkwOTuUfLK3HNwiDm8',
    appId: '1:870875139309:android:e8e6861cb99ade9dbb50e4',
    messagingSenderId: '870875139309',
    projectId: 'contact-app-9cc96',
    storageBucket: 'contact-app-9cc96.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2NXtFSgLrdpKa6fKuXOjp-6Bi4ZYVWZE',
    appId: '1:870875139309:ios:13c803bd772b3d9fbb50e4',
    messagingSenderId: '870875139309',
    projectId: 'contact-app-9cc96',
    storageBucket: 'contact-app-9cc96.appspot.com',
    iosBundleId: 'com.example.contactsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2NXtFSgLrdpKa6fKuXOjp-6Bi4ZYVWZE',
    appId: '1:870875139309:ios:1800738c633b69cabb50e4',
    messagingSenderId: '870875139309',
    projectId: 'contact-app-9cc96',
    storageBucket: 'contact-app-9cc96.appspot.com',
    iosBundleId: 'com.example.contactsApp.RunnerTests',
  );
}
